import { NextRequest, NextResponse } from "next/server";
import { protectPdf, cleanupTempDirectory } from "@/services/pdf/protectUnlockService";
import { writeFile, readFile, mkdir } from "node:fs/promises";
import * as path from "node:path";
import * as crypto from "node:crypto";
import { tmpdir } from "node:os";

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData();
    const file = formData.get("file") as File;
    const userPassword = formData.get("userPassword") as string;
    const ownerPassword = formData.get("ownerPassword") as string | undefined;
    const encryptionLevel = (formData.get("encryptionLevel") as "aes-128" | "aes-256") || "aes-256";
    const printPermission = formData.get("printPermission") as "full" | "low" | "none" | undefined;
    const modifyPermission = formData.get("modifyPermission") as "all" | "annotate" | "form" | "assembly" | "none" | undefined;
    const copyPermission = formData.get("copyPermission") as "y" | "n" | undefined;
    const annotatePermission = formData.get("annotatePermission") as "y" | "n" | undefined;
    const fillFormPermission = formData.get("fillFormPermission") as "y" | "n" | undefined;
    const extractPermission = formData.get("extractPermission") as "y" | "n" | undefined;
    const assemblePermission = formData.get("assemblePermission") as "y" | "n" | undefined;
    const printHighResPermission = formData.get("printHighResPermission") as "y" | "n" | undefined;

    if (!file) {
      return NextResponse.json(
        { success: false, error: "No file provided" },
        { status: 400 }
      );
    }

    if (!userPassword) {
      return NextResponse.json(
        { success: false, error: "User password is required" },
        { status: 400 }
      );
    }

    if (userPassword.length < 8) {
      return NextResponse.json(
        { success: false, error: "Password must be at least 8 characters" },
        { status: 400 }
      );
    }

    const uniqueId = crypto.randomUUID();
    const tempDir = path.join(tmpdir(), `pdfmedic-uploads-${uniqueId}`);
    await mkdir(tempDir, { recursive: true });
    const inputPath = path.join(tempDir, `input-${uniqueId}.pdf`);

    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    await writeFile(inputPath, buffer);

    try {
      const result = await protectPdf({
        inputPath,
        outputPath: "", // Will be generated by the service
        userPassword,
        ownerPassword,
        encryptionLevel,
        restrictions: {
          print: printPermission,
          modify: modifyPermission,
          copy: copyPermission,
          annotate: annotatePermission,
          fillForm: fillFormPermission,
          extract: extractPermission,
          assemble: assemblePermission,
          printHighResolution: printHighResPermission,
        },
      });

      // Read the protected PDF
      const protectedBuffer = await readFile(result.outputPath);
      const protectedFileName = `protected-${file.name.replace(/\.pdf$/i, "")}.pdf`;

      // Cleanup temp files
      await cleanupTempDirectory(path.dirname(inputPath));
      await cleanupTempDirectory(path.dirname(result.outputPath));

      // Return the protected PDF as a download
      return new NextResponse(protectedBuffer as unknown as BodyInit, {
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="${protectedFileName}"`,
          "Content-Length": protectedBuffer.length.toString(),
        },
      });
    } catch (serviceError) {
      // Cleanup on error
      await cleanupTempDirectory(path.dirname(inputPath));
      throw serviceError;
    }
  } catch (error) {
    console.error("Protect PDF API error:", error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Failed to protect PDF",
      },
      { status: 500 }
    );
  }
}