import { NextRequest, NextResponse } from "next/server";
import { unlockPdf, cleanupTempDirectory } from "@/services/pdf/protectUnlockService";
import { writeFile, readFile, mkdir } from "node:fs/promises";
import * as path from "node:path";
import * as crypto from "node:crypto";
import { tmpdir } from "node:os";

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData();
    const file = formData.get("file") as File;
    const password = formData.get("password") as string;

    if (!file) {
      return NextResponse.json(
        { success: false, error: "No file provided" },
        { status: 400 }
      );
    }

    if (!password) {
      return NextResponse.json(
        { success: false, error: "Password is required" },
        { status: 400 }
      );
    }

    const uniqueId = crypto.randomUUID();
    const tempDir = path.join(tmpdir(), `pdfmedic-uploads-${uniqueId}`);
    await mkdir(tempDir, { recursive: true });
    const inputPath = path.join(tempDir, `input-unlock-${uniqueId}.pdf`);

    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    await writeFile(inputPath, buffer);

    try {
      const result = await unlockPdf({
        inputPath,
        outputPath: "", // Generated by the service
        password,
      });

      // Read the unlocked PDF
      const unlockedBuffer = await readFile(result.outputPath);
      const unlockedFileName = `unlocked-${file.name.replace(/\.pdf$/i, "")}.pdf`;

      // Cleanup temp files
      await cleanupTempDirectory(path.dirname(inputPath));
      await cleanupTempDirectory(path.dirname(result.outputPath));

      // Return the unlocked PDF as a download
      return new NextResponse(unlockedBuffer as unknown as BodyInit, {
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="${unlockedFileName}"`,
          "Content-Length": unlockedBuffer.length.toString(),
        },
      });
    } catch (serviceError) {
      // Cleanup on error
      await cleanupTempDirectory(path.dirname(inputPath));
      throw serviceError;
    }
  } catch (error) {
    console.error("Unlock PDF API error:", error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Failed to unlock PDF",
      },
      { status: 500 }
    );
  }
}
